---
- name: Create Amazon Connect instance
  shell: |
    aws connect create-instance \
        --instance-alias {{ connect_alias }} \
        --identity-management-type SAML \
        --inbound-calls-enabled \
        --outbound-calls-enabled \
        --region {{ region }}
  register: instance_create
  changed_when: "'Id' in instance_create.stdout"
- name: Copy JSON
  copy:
    src: files/ivr_contact_flow.json
    dest: /tmp/ivr_contact_flow.json
- name: Parse instance ID
  set_fact:
    instance_id: "{{ instance_create.stdout | from_json | json_query('Id') }}"

- debug:
    msg: "Connect instance created. ID = {{ instance_id }}"

- name: Wait for Connect instance to be active
  command: aws connect describe-instance --instance-id {{ instance_id }} --region us-east-1
  register: instance_status
  retries: 20
  delay: 30
  until: "'IN_PROGRESS' not in instance_status.stdout and instance_status.rc == 0"

- name: Upload Contact Flow (IVR)
  shell: |
    aws connect create-contact-flow \
        --instance-id {{ instance_id }} \
        --name "{{ flow_name }}" \
        --type CONTACT_FLOW \
        --content file:///tmp/ivr_contact_flow.json \
        --region {{ region }}
  register: flow_upload

- name: Parse Flow ID
  set_fact:
    flow_id: "{{ flow_upload.stdout | from_json | json_query('ContactFlowId') }}"

- debug:
    msg: "Uploaded IVR Contact Flow. Flow ID = {{ flow_id }}"

- name: Claim phone number
  shell: |
    aws connect claim-phone-number \
        --phone-number {{ phone_number }} \
        --target-arn {{ instance_id }} \
        --phone-number-type DID \
        --region {{ region }}
  register: phone_claim

- name: Parse Phone Number ID
  set_fact:
    phone_id: "{{ phone_claim.stdout | from_json | json_query('PhoneNumberId') }}"

- debug:
    msg: "Claimed phone number. Phone ID = {{ phone_id }}"

- name: Assign IVR flow to phone number
  shell: |
    aws connect update-phone-number \
        --phone-number-id {{ phone_id }} \
        --target-arn {{ instance_id }} \
        --contact-flow-id {{ flow_id }} \
        --region {{ region }}
  register: assign_flow

- debug:
    msg: "Phone number successfully linked to IVR flow!"